### ISSUE TITLE
missing recipes for certain items

### ISSUE THREAD

**Issue by SpiderOverlord** [InfinityRaider/NinjaGear#1]
for some reason the ninja armor, and ninja ropes don't have recipes, and I use jei

**Comment by InfinityRaider** [comment]
Are the recipes just not showing up in JEI or are they also not working?

**Comment by SpiderOverlord** [comment]
I can't craft the items in question

**Comment by InfinityRaider** [comment]
That's strange, I can't reproduce this. I've also seen others successfully crafting everything, so I have no clue why you are having this issue.

**Comment by InfinityRaider** [comment]
I managed to fix this in InfinityLib: https://github.com/InfinityRaider/InfinityLib/commit/46240e23e8bd236e1de732b31c0195581884837d
