### ISSUE TITLE
Dupe bug

### ISSUE THREAD

**Issue by KamiSami** [InfinityRaider/NinjaGear#10]
Okay hopefully this is last one for now... Basically, if you attack rope to ceiling, and shift click the rope off, the ceiling block stays normally where it is placed but copy of the ceiling block drops... Making it efficient duping method.

#8 Has info which forge and ninja gear i have been using for the bugs i mentioned today.

**Comment by InfinityRaider** [comment]
This is bad...
I'll fix it asap
