### ISSUE TITLE
[1.9.4] Placing Ropes causes crash (Major Bug)

### ISSUE THREAD

**Issue by jawsawn** [InfinityRaider/NinjaGear#2]
I placed a rope under a giant mushroom and it crashed me, now the world is corrupted.

**Comment by InfinityRaider** [comment]
A crash log would be nice.

**Comment by jawsawn** [comment]
oh i didnt include one? Sorry I thought I did. 

Doesn't placing ropes under the brown mushroom blocks cause it?  I'm not with my pc at so i cant cause it yet.

**Comment by OhiraKyou** [comment]
I'm guessing @JAWSAWN simply has OptiFine installed, which does cause some mods that don't support it to crash (with the mushroom being unrelated). To fix the world, try loading it with OptiFine disabled to remove the rope.

Here's a [crash report](http://pastebin.com/yZGE3hwC).

Minecraft 1.9.4
Forge 1.9.4-12.17.0.1951
OptiFine 1.9.4_HD_U_B5
NinjaGear 1.9.4-0.0.2

**Comment by InfinityRaider** [comment]
If this is truly Optifine related, then sorry I can't and won't do anything. None of my mods support Optifine, and they never will.
If it still crashes without Optifine, then I will need a crash log.

**Comment by InfinityRaider** [comment]
CLosing since lack of response and probably incompatibility with Optifine
