### ISSUE TITLE
Missing Texture - Rope Coil

### ISSUE THREAD

**Issue by rckymtnrfc** [InfinityRaider/NinjaGear#5]
I'm getting a missing texture for the Rope Coil.  I checked and the texture is in the jar.  I tried rename it from ropecoil to ropeCoil but no luck.  

Thank you

**Comment by InfinityRaider** [comment]
I've noticed this as well, I'll have to investigate.
Chances are the port to InfinityLIb will have fixed this, not sure though.

**Comment by InfinityRaider** [comment]
I have confirmed that this is fixed witht he port to InfinityLib, update will be released soon.
