### ISSUE TITLE
[Bug] Crashing in the nether

### ISSUE THREAD

**Issue by MysticAura** [InfinityRaider/NinjaGear#6]
MC: 1.10.2
Forge: 2151
Mod: ninjagear-0.0.3

Not sure if it's relation dependant, but server players keep having this crash.

[Crash Log](http://pastebin.com/sZKVDTL3)

**Comment by InfinityRaider** [comment]
Ah shit, this is why I made InfinityLib...

Its a bug in my code which I use in all of my mods, I fixed it ages ago, but forgot to fix it in the NinjaGear code, it'll be fixed when I put out the next version of NinjaGear (which will have InfinityLib as a dependency).
Should be this weekend, thanks for reporting this.

**Comment by InfinityRaider** [comment]
Fix will be on CurseForge later today
