### ISSUE TITLE
Server crash when in stealth and hitting mob

### ISSUE THREAD

**Issue by KamiSami** [InfinityRaider/NinjaGear#8]
Hi, it seems i am getting server crash when i hit enemy in stealth mode with this in the server log: https://pastebin.com/wX5SjUTC

I should mention that all the bugs i have today mentioned happened in forge version of 36.1.24 and mod version of ninjagear-2.0.2

**Comment by InfinityRaider** [comment]
Im probably calling a client only method somewhere, I'll look into it.

**Comment by InfinityRaider** [comment]
I am failing to reproduce this, which mob are you hitting, does this also happen with only InfinityLib + NinjaGear?
Is this on a dedicated server, or is this in singleplayer?
If it is a dedicated server, does it also happen in singleplayer?

**Comment by KamiSami** [comment]
It was zombie when i tried sneak and hit it from behind. And it happened in serverside. If it cannot be reproduces it is mostlikely mod incompatibility, not sure what could possibly cause it though if the crash log did not mention anything what it could have been...

**Comment by InfinityRaider** [comment]
~~I can't figure this one out, does it also happen with just NinjaGear and InfinityLib?~~

Ok I can reproduce it, once I changed my gamemode to survival it does indeed happen, I'll try to figure out a fix.
