### ISSUE TITLE
Katana does low damage despite empty off-hand

### ISSUE THREAD

**Issue by KamiSami** [InfinityRaider/NinjaGear#9]
Title pretty much, if this isn't reproduceable then it has to be some mod conflict

#8 Has info about which forge version and ninjagear i have been using.

**Comment by InfinityRaider** [comment]
Does this also happen in singleplayer, or only on a server?

**Comment by KamiSami** [comment]
Yes, it seems it happens in singleplayer aswell, decription says i should deal 9 half hearts of damage (as i have quark installed), but i deal only 4. (Toro Damage Indicators mod shows the damage done) So it takes 3 hits to kill cow. Also something i noticed, if you have katana in off-hand you do 4 fist damage aswell, which i assume is unintended?
